### PR TITLE
Add a 'test' action to blacklist things. 

### PR DESCRIPTION
**Pull request by 0mark**
I tried to do a rebase, but failed. Git always gets the better of me.
I just forked it anew, i hope that causes no trouble.
thanks
nullmark

### CODE REVIEW

**Comment by 0mark** [comment]
Poke :)

**Comment by LemonBoy** [comment]
Hey, I'm currently busy as hell and am rewriting some chunks of ldm in the meanwhile and have incorporated part of this PR :)
I'll try to finish it as soon as possible and merge the test callback in too!

**Comment by LemonBoy** [comment]
On a side note, what's the use case for this ?

**Comment by 0mark** [comment]
Well, flexible and simple blacklisting:
- by filesystem (eg "crypto_LUKS", or very old/experimental stuff)
- by name (eg "IPOD", "*RECOVERY*", "DONT_MOUNT", ...)
- by node (eg mapper "/dev/mapper/dm-*", ...)
- by arbitrary conditions (vendor, driver, USB Port, ...)
The latter ones are not simple anymore, but very useful sometimes :)

**Comment by LemonBoy** [comment]
Well, for the most common blacklisting needs I'd recommend using the fstab method (this covers your second case).
There shouldn't be any problem with processing the LUKS (it'd be cool to have support for encrypted devices :) or device mappers since those are directly discarded.
As for the latest example, I can't think of a way to associate the device with its usb port number or driver or vendor, at least not without many jumps.

**Comment by 0mark** [comment]
Sure, the fstab way works, but i soon had tens of blacklisting entries. I stopped when i had more blacklists than actual mounts in the fstab. In adition, its easier to just add another name to the list of blacklisted names (for example). Or have that list in a differen file, maybe writable by some groups.

I think i remember that i blacklisted dm-* nodes because they where mounted by ldm.

As for the latest, you can start by 
 /sys/dev/block/MAJOR:MINOR/NODE/
and then go on as usual.

**Comment by LemonBoy** [comment]
The problem with /dev/dm-* sounds like a bug that has been fixed a while ago (iirc).
Support for encrypted filesystems can be added by using libcryptsetup, the boring part is writing a crypttab parser.

**Comment by 0mark** [comment]
Good to now :)
But nonetheless, i think the genreal use case is unaffected. For example, i have blacklisted HFS partions. And devices that are not partioned at all.

I think the best argument is the ease of use and the flexibility. I disabled auto mounting of rescue partions, weird special partions on some usb sticks, some specific devices which may fail when mounted (some rockbox instances can have that), let alone a fistful of things by name. Having the fstab readable again is nice enough ;)
And i think about disabling auto mounting for partitions with the dirty bit set and everything on a dedicated usb port.

**Comment by LemonBoy** [comment]
Would it be possible to rebase the commit (only the first one's useful) ? :)

**Comment by 0mark** [comment]
I think i did something wrong here, there should be only one commit anyway. The others are completely unrelated. I think i messed something up. I try to fix it (probably not before weekend). Sorry :)

**Comment by LemonBoy** [comment]
Ping ? :)

**Pull request closed without merging**
